"""Canonical repo-relative paths for FOMS harness assets."""

from __future__ import annotations

HARNESS_DOCS_DIR = "docs/harness"
HARNESS_POLICY_DIR = f"{HARNESS_DOCS_DIR}/policy"
HARNESS_RUNTIME_DIR = f"{HARNESS_DOCS_DIR}/runtime"
HARNESS_LOGS_DIR = f"{HARNESS_DOCS_DIR}/logs"

HARNESS_DECISIONS_PATH = f"{HARNESS_POLICY_DIR}/DECISIONS.md"
HARNESS_INCIDENT_TEMPLATE_PATH = f"{HARNESS_POLICY_DIR}/INCIDENT_TEMPLATE.md"

