"""Compatibility shim for the canonical `foms.services.erp_display` module."""

from foms.services.erp_display import (
    _can_modify_sales_domain,
    _drawing_next_action_text,
    _drawing_status_label,
    _ensure_dict,
    _erp_alerts,
    _erp_get_stage,
    _erp_get_urgent_flag,
    _erp_has_media,
    _extract_name_candidate,
    _lookup_user_name_from_candidate,
    _manager_candidates,
    _normalize_date_to_yyyymmdd,
    _sales_domain_fallback_match,
    apply_erp_display_fields,
    apply_erp_display_fields_to_orders,
    clean_dict_like_name,
    get_today_kst,
    normalize_manager_name,
    self_measurement_four_checks_done,
)

__all__ = [
    "get_today_kst",
    "self_measurement_four_checks_done",
    "_extract_name_candidate",
    "_manager_candidates",
    "_lookup_user_name_from_candidate",
    "normalize_manager_name",
    "clean_dict_like_name",
    "_ensure_dict",
    "_normalize_date_to_yyyymmdd",
    "apply_erp_display_fields",
    "_erp_get_urgent_flag",
    "_erp_get_stage",
    "_erp_has_media",
    "_erp_alerts",
    "_sales_domain_fallback_match",
    "_can_modify_sales_domain",
    "_drawing_status_label",
    "_drawing_next_action_text",
    "apply_erp_display_fields_to_orders",
]
