"""Add is_self_measurement field to Order model

Revision ID: 7e2514f54d04
Revises: aef164da4c43
Create Date: 2025-07-24 11:52:45.210445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2514f54d04'
down_revision: Union[str, None] = 'aef164da4c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_logs', 'order_id')
    op.drop_column('access_logs', 'message')
    op.add_column('orders', sa.Column('is_self_measurement', sa.Boolean(), nullable=True))
    op.drop_column('orders', 'regional_measurement_upload')
    op.drop_column('orders', 'regional_contract_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('regional_contract_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('regional_measurement_upload', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('orders', 'is_self_measurement')
    op.add_column('access_logs', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('access_logs', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
