"""Add measurement_completed and construction_type to orders table

Revision ID: aef164da4c43
Revises: 
Create Date: 2025-06-11 10:25:55.878217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef164da4c43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('access_logs', 'order_id')
    # op.drop_column('access_logs', 'message')
    op.add_column('orders', sa.Column('measurement_completed', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('construction_type', sa.String(length=50), nullable=True))
    # op.drop_column('orders', 'regional_measurement_upload')
    # op.drop_column('orders', 'regional_contract_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('orders', sa.Column('regional_contract_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # op.add_column('orders', sa.Column('regional_measurement_upload', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('orders', 'construction_type')
    op.drop_column('orders', 'measurement_completed')
    # op.add_column('access_logs', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.add_column('access_logs', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
